"""transaction table modified

Revision ID: 7a51a747035b
Revises: 0fa97a6606f7
Create Date: 2024-07-15 17:38:05.444781

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a51a747035b'
down_revision = '0fa97a6606f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_transactions')
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('ship_id', sa.Integer(), nullable=True))
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('amount',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_foreign_key(batch_op.f('fk_transactions_ship_id_ships'), 'ships', ['ship_id'], ['id'])
        batch_op.drop_column('description')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.VARCHAR(length=255), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_transactions_ship_id_ships'), type_='foreignkey')
        batch_op.alter_column('amount',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('ship_id')
        batch_op.drop_column('category')

    op.create_table('_alembic_tmp_transactions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('amount', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('category', sa.VARCHAR(), nullable=False),
    sa.Column('ship_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['ship_id'], ['ships.id'], name='fk_transactions_ship_id_ships'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_transactions_user_id_users'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
